services:
  client-dev:
    image: hallert60/guitar-tab-site-client-dev
    profiles:
      - dev
    container_name: client-dev
    depends_on:
      - db-dev
    build:
      context: .
    ports:
      - 4000:3000
    environment:
      - WATCHPACK_POLLING=true
      - AUTH0_SECRET=auth0secret
      - AUTH0_BASE_URL=http://localhost:4000
      - API_URL=http://localhost:4000
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db-dev
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=database
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  client-e2e:
    image: hallert60/guitar-tab-site-client-e2e
    healthcheck:
      test: ['CMD-SHELL', 'wget -O /dev/null http://localhost:3000 || exit 1']
      timeout: 10s
    profiles:
      - e2e
    container_name: client-e2e
    depends_on:
      - db-e2e
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - AUTH0_SECRET=auth0secret
      - AUTH0_BASE_URL=http://localhost:3000
      - API_URL=http://localhost:3000
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db-e2e
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=database
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  db-dev:
    container_name: db-dev
    profiles:
      - dev
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./postgres_scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  db-e2e:
    container_name: db-e2e
    profiles:
      - e2e
    image: postgres
    expose:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    volumes:
      - ./postgres_scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  playwright-test:
    image: hallert60/guitar-tab-e2e
    expose:
      - 9009:9009
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./playwright-report:/app/playwright-report
    container_name: playwright-test
    network_mode: host
    profiles:
      - e2e
    command: npx playwright test --workers 1 --trace on
    depends_on:
      client-e2e:
        condition: service_healthy

volumes:
  postgres-db-volume:
