version: '3.8'

services:
  client:
    depends_on:
      - db
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - MONGO_URI=mongodb://db/db_data
      - SESSION_SECRET=secret
      - ENCRYPTION_KEY=encryptionkey
      - NODE-ENV=development
      - API_URL=http://localhost:3000
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=database
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres-db-volume:
