version: '3.8'

services:
  client:
    depends_on:
      - db
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - MONGO_URI=mongodb://db/db_data
      - SESSION_SECRET=secret
      - ENCRYPTION_KEY=encryptionkey
      - NODE-ENV=development
      - API_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  db:
    image: mongo:6.0.13
    volumes:
      - ./db_data:/data/db
    ports:
      - '27018:27017'
volumes:
  db_data:
