name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    timeout-minutes: 60
    steps:
      - name: pnpm-setup
        with:
          version: latest
        uses: pnpm/action-setup@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: pnpm install --frozen-lockfile
      - run: npx playwright install --with-deps
      - run: docker compose build
      - run: docker compose --profile e2e up
      - run: npx playwright test
