name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    timeout-minutes: 60
    steps:
      - name: pnpm-setup
        with:
          version: latest
        uses: pnpm/action-setup@v4

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npx playwright install --with-deps

      - name: Install Deps
        run: pnpm install

      - run: docker compose up playwright-test
