name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
  EMAIL_1: ${{secrets.EMAIL_1}}
  PASSWORD_1: ${{secrets.PASSWORD_1}}
  EMAIL_2: ${{secrets.EMAIL_2}}
  PASSWORD_2: ${{secrets.PASSWORD_2}}

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: npm install -g pnpm

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create env file
        run: |
          touch .env
          echo AUTH0_ISSUER_BASE_URL=${{ env.AUTH0_ISSUER_BASE_URL }} >> .env
          echo AUTH0_CLIENT_ID =${{ env.AUTH0_CLIENT_ID  }} >> .env
          echo AUTH0_CLIENT_SECRET=${{ env.AUTH0_CLIENT_SECRET}} >> .env
          echo EMAIL_1=${{ env.EMAIL_1 }} >> .env
          echo PASSWORD_1=${{ env.PASSWORD_1 }} >> .env
          echo EMAIL_2=${{ env.EMAIL_2 }} >> .env
          echo PASSWORD_2=${{ env.PASSWORD_2 }} >> .env

      - name: 'RUNNER TEMP'
        run: echo "${{ runner.temp }}"

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Run e2e Tests
        run: pnpm run docker-test

      - run: sleep infinity

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
