name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    timeout-minutes: 60
    steps:
      - run: npm install -g pnpm

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - run: pnpm run docker-test

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
