name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    timeout-minutes: 60
    environment: CI
    env:
      AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
      EMAIL_1: ${{secrets.EMAIL_1}}
      PASSWORD_1: ${{secrets.PASSWORD_1}}
      EMAIL_2: ${{secrets.EMAIL_2}}
      PASSWORD_2: ${{secrets.PASSWORD_2}}

    steps:
      - run: npm install -g pnpm

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ENV VARIB
        run: echo "$EMAIL_1" | cut -c 1-7

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Run e2e Tests
        run: pnpm run docker-test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
