name: practice

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  vitest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: pnpm-setup
        with:
          version: latest
        uses: pnpm/action-setup@v4

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm test
